- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Install Docker dependencies
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: latest
    update_cache: true

- name: Allow running Docker without sudo
  user:
    name: "{{ ansible_user | default('vagrant') }}"
    groups: docker
    append: yes

- name: Restart docker to apply group changes
  systemd:
    name: docker
    state: restarted
    enabled: yes

- name: Ensure Docker service is started and enabled
  systemd:
    name: docker
    enabled: true
    state: started