pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = "frontend"
        FRONTEND_DOCKERFILE_SPURCE = "HW_03/project/frontend/"
    }

    stages {
        stage('SonarQube') {
            steps {
                echo "- SonarQube's testing..."
                // 
                echo "- SonarQube's testing is done"
            }
        }
        stage('Docker image') {
            steps {
                dir("$FRONTEND_DOCKERFILE_SPURCE") {
                    echo "- Building the docker image ${DOCKER_IMAGE_NAME}..."
                    sh "docker build -t ${DOCKER_IMAGE_NAME} ."
                    echo "- The docker image: ${DOCKER_IMAGE_NAME} was built successfully"
                }
            }
        }
    }
}
