################################################
version: '3.8'
services:
################################################
  app:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    depends_on:
      - db
################################################
  db:
    image: postgres:13.18-alpine3.20
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
################################################
