################################################
version: '3.8'
services:
################################################
  app:
    build:
      context: ./python
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
      - "~/.ssh:/root/.ssh:ro"
    depends_on:
      - db
################################################
  db:
    image: postgres:12.0-alpine
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
################################################
