#############################################
- name: Generate Dockerfiles
  template:
    src: "{{ role_path }}/templates/{{ item.name }}_Dockerfile.j2"
    dest: "{{ role_path }}/.../Dockerfile" # write a path where to store a file
  loop: "{{ docker_images }}"
#############################################
- name: Generate the .env file
  template:
    src: "{{ role_path }}/templates/{{ item.name }}.j2"
    dest: "{{ role_path }}/.../{{ item.name }}" # write a path where to store a file
  loop: "{{ env_file }}"
#############################################
- name: Generate the docker-compose.yml file
  template:
    src: "{{ role_path }}/templates/{{ item.name }}.j2"
    dest: "{{ role_path }}/.../{{ item.name }}.yml" # write a path where to store a file
  loop: "{{ docker_compose_config }}"
  loop_control:
    label: "{{ item.name }}"
  tags:
    - docker
#############################################