# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "server_1" do |server_1|
      config.vm.box = "ubuntu/trusty64"
      config.vm.network "private_network", ip: "192.168.56.99"
    end

    config.vm.define "server_2" do |server_2|
      config.vm.box = "ubuntu/trusty64"
      config.vm.network "private_network", ip: "192.168.56.45"
    end

    config.vm.define "server_3" do |server_3|
      config.vm.box = "ubuntu/trusty64"
      config.vm.network "private_network", ip: "192.168.56.190"
    end
end
