# -*- mode: ruby -*-
# vi: set ft=ruby :
######################################################################
Vagrant.configure("2") do |config|
  (1..3).each do |i|
    vm_name = "server-#{i}"
    config.vm.define vm_name do |vm|
      vm.vm.box = "ubuntu/jammy64"
      vm.vm.hostname = vm_name
      vm.vm.network "private_network", ip: "192.168.56.#{100 + i}"
      vm.vm.provider "virtualbox" do |vb|
        vb.name = vm_name
        vb.memory = 512
        vb.cpus = 1
      end
    end
  end
end
######################################################################
