# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    ############################################################
    config.vm.define "server_1" do |server_1|
      server_1.vm.box = "ubuntu/jammy64"
      server_1.vm.network "private_network", ip: "192.168.56.99"
      server_1.vm.provision :shell, path: "sftp_config_file.sh"

      server_1.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
    ############################################################ 
    config.vm.define "server_2" do |server_2|
      server_2.vm.box = "ubuntu/jammy64"
      server_2.vm.network "private_network", ip: "192.168.56.45"
      server_2.vm.provision :shell, path: "sftp_config_file.sh"

      server_2.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
    ############################################################
    config.vm.define "server_3" do |server_3|
      server_3.vm.box = "ubuntu/jammy64"
      server_3.vm.network "private_network", ip: "192.168.56.190"
      server_3.vm.provision :shell, path: "sftp_config_file.sh"

      server_3.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = 2
      end
    end
    ############################################################
end
