################################################
version: '3.8'
services:
################################################
  backend:
    image: dolvladzio/backend
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      # PostgreSQL env
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_PORT: ${DB_PORT}
      # Redis env
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - new_network
################################################
  proxy_pass:
    build:
      context: ./proxy_pass
    image: proxy_pass
    container_name: proxy_pass
    restart: always
    ports:
      - "3000:3000"
    networks:
      - new_network
################################################
  frontend:
    image: dolvladzio/frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgres
      - backend
    networks:
      - new_network
################################################
  postgres:
    build:
      context: ./postgres
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - new_network
################################################
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    networks:
      - new_network
################################################
networks:
  new_network:
################################################
