pipeline {
    agent any

    environment {
        DOCKER_IMAGE_NAME = "backend"
    }

    stages {
        stage('SonarQube') {
            steps {
                echo "- SonarQube's testing..."
                // 
                echo "- SonarQube's testing is done"
            }
        }
        stage('Docker image') {
            steps {
                echo "- Building the docker image ${DOCKER_IMAGE_NAME}..."
                sh "docker build -t ${DOCKER_IMAGE_NAME} ."
                echo "- The docker image: ${DOCKER_IMAGE_NAME} was built successfully"
            }
        }
    }
}
