pipeline {
    agent any
    tools {
        gradle "Gradle 7.5.1"
    }

    environment {
        // Dynamically generate a timestamp
        CURRENT_TIMESTAMP = new Date().format('yyyy-MM-dd-HH-mm-ss', TimeZone.getTimeZone('UTC'))
        // Frontend
        frontend_docker_image_name = "frontend-${CURRENT_TIMESTAMP}"
        frontend_dockerfile_source = "HW_03/project/frontend/"
        frontend_service_name      = "frontend"
        frontend_sonar_command     = "npm run sonar"
        // Backend
        backend_docker_image_name = "frontend-${CURRENT_TIMESTAMP}"
        backend_dockerfile_source = "HW_03/project/"
        backend_service_name      = "backend"
        backend_sonar_command     = "gradle sonar"
        // Docker
        docker_cred_id            = "03f97223-5b61-4175-b3e8-650d4de0e795"
    }

    stages {
        // stage('Test') {
        //     steps {
        //         script {
        //             // The frontend's sonarqube testing
        //             sonarqubeTest(frontend_sonar_command, frontend_dockerfile_source, frontend_service_name)
        //             // The backend's sonarqube testing
        //             sonarqubeTest(backend_sonar_command, backend_dockerfile_source, backend_service_name)
        //         }
        //     }
        // }
        // stage('Build') {
        //     steps {
        //         script {
        //             // The frontend's image building
        //             buildImageStage(frontend_docker_image_name, frontend_dockerfile_source)
		//             // The backend's image building
        //             buildImageStage(backend_docker_image_name, backend_dockerfile_source)
        //         }
        //     }
        // }
        stage('Logging') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: "$docker_cred_id", 
                                                    usernameVariable: 'DOCKER_USERNAME', 
                                                    passwordVariable: 'DOCKER_PASSWORD')]) {
                        // Use the credentials here
                        sh """
                        echo "Logging into DockerHub"
                        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
                        """
                    }
                }
            }
        }
        stage('Deploy') {
            steps {
                script {
                    // Deploying the frontend's image to the dockerhub
		            // Deploying the backend's image to the dockerhub
                }
            }
        }
        stage('Cleanup') {
            steps {
                script {
                    // Deleting all images and cleaning the docker's system
                    // sh "docker image prune -a && docker system prune --volumes"
                }
            }
        }
    }

    post {
        always {
            echo "- Pipeline comleted!"
        }
        success {
            echo '- Deployment to staging successful!'
        }
        failure {
            echo '- Pipeline failed! Check the logs for errors.'
        }
    }
}

// A function to use SonarQube
def sonarqubeTest(String command, String dockerfileSource, String serviceName) {
    stage("- Testing: ${serviceName}") {
        dir("${dockerfileSource}") {
            sh "${command}"
            echo "- ${serviceName} was tested successfully via SonarQube"
        }
    }
}
// A function to build images
def buildImageStage(String dockerImageName, String dockerfileSource) {
    stage("- Building: ${dockerImageName}") {
        dir("${dockerfileSource}") {
            echo "- Building the docker image: ${dockerImageName}..."
            sh "docker build -t ${dockerImageName} ."
            echo "- The docker image: ${dockerImageName} was built successfully"
        }
    }
}