pipeline {
    agent any

    environment {
        // Frontend
        FRONTEND_DOCKER_IMAGE_NAME = "frontend"
        FRONTEND_DOCKERFILE_SOURCE = "HW_03/project/frontend/"
        // Backend
        BACKEND_DOCKER_IMAGE_NAME = "backend"
        BACKEND_DOCKERFILE_SOURCE = "HW_03/project/"
    }

    stages {
        stage("- Frontend's Stage") {
            steps {
                script {
                    def build_image_stage = load 'jenkins/build-image.groovy'
                    build_image_stage(FRONTEND_DOCKER_IMAGE_NAME, FRONTEND_DOCKERFILE_SOURCE)
                }
            }
        }
        stage("- Backend's Stage") {
            steps {
                script {
                    def build_image_stage = load 'jenkins/build-image.groovy'
                    build_image_stage(BACKEND_DOCKER_IMAGE_NAME, BACKEND_DOCKERFILE_SOURCE)
                }
            }
        }
    }
}
