docker_images:
#############################################
  - name: postgres
    postgres_version: 12.0-alpine
#############################################
  - name: proxy_pass
    nginx_version: stable-alpine3.20-slim
#############################################
  - name: frontend
    node_version: 20-alpine
    react_app_api_base_url: /api
    nginx_version: stable-alpine3.20-slim
    expose: 80
#############################################
  - name: backend
    gradle_version: 7.5.1-jdk11
    tomcat_version: 9.0.104-jre11-temurin-jammy
    expose: 8080
#############################################
env_file:
  - name: .env
    postgres_db: database
    postgres_user: db_user
    postgres_password: db_pass
    db_host: postgres
    db_port: 5432
    redis_host: redis
    redis_port: 6379
#############################################
docker_compose_config:
  - name: docker-compose
    version: 3.8
    # Backend
    backend_port: 8080:8080
    backend_image_name: backend
    backend_container_name: backend
    # Frontend
    frontend_port: 80:80
    frontend_image_name: frontend
    frontend_container_name: frontend
    # Proxy_pass
    proxy_pass_port: 3000:3000
    proxy_pass_image_name: backend
    proxy_pass_container_name: backend
    # Redis
    redis_image: alpine
    # All
    networks: new_network
#############################################