name: CI_Testing_Frontend-Backend

on:
  push:
    branches: [ "SCRUM-18-HW_03" ]
  pull_request:
    branches: [ "SCRUM-18-HW_03" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
######################################################
    - name: Creating .env file with necessary envs
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env
######################################################
    - name: Setup all infrastructure
      run: docker compose up -d
