################################################
version: '3.8'
services:
################################################
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   restart: aalways
  #   ports:
  #     - "8080:8080"
################################################
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  #     - backend
################################################
  db:
    image: postgres:12.0-alpine
    restart: always
    container_name: db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
################################################
