################################################
version: '3.8'
services:
################################################
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      MONGODB_NAME: ${MONGODB_NAME}
      MONGODB_CLUSTER: ${MONGODB_CLUSTER}
      REDIS_HOST: ${REDIS_HOST}
    ports:
      - "8080:8080"
    depends_on:
      - db
################################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
      - backend
################################################
  db:
    image: postgres:12.0-alpine
    container_name: db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
################################################
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
################################################
