################################################
version: '3.8'
services:
################################################
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend
    restart: always
    env_file:
      - .env
    environment:
      # PostgreSQL env
      DB_HOST: ${DB_HOST}
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      # Redis env
      REDIS_HOST: ${REDIS_HOST}
      # MongoDB env
      MONGODB_NAME: ${MONGODB_NAME}
      MONGODB_CLUSTER: ${MONGODB_CLUSTER}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
################################################
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - postgres
      - backend
################################################
  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
################################################
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
################################################
  mongodb:
    # image: karimtemple/mongo
    image: mongo:noble
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
################################################
